[build-system]
requires = ["setuptools", "build","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "src_module"
version = "0.1.1-9"

[tool.setuptools.packages.find]
where = ["."]
include = ["src_module*"]

[project.scripts]
pipe1 = "src_module.pipelines.pipe1:run"
pipe2 = "src_module.pipelines.pipe2:run"

